apiVersion: core.rancher-operator.io/v1alpha1
kind: ClusterPrerequisites
metadata:
  labels:
    app.kubernetes.io/name: rancher-operator
    app.kubernetes.io/managed-by: kustomize
  name: clusterprerequisites-sample
spec:
  # TODO(user): Add fields here
